package com.weixin.datacore.domain.weixin.model;
// default package
// Generated 2014-2-10 14:50:02 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WeixinArticlesMulti generated by hbm2java
 */
@Entity
@Table(name = "weixin_articles_multi", catalog = "jforum")
public class WeixinArticlesMulti implements java.io.Serializable {

	private Long id;
	private Long articlesId;
	private String title;
	private String description;
	private String url;
	private String picUrl;

	public WeixinArticlesMulti() {
	}

	public WeixinArticlesMulti(Long articlesId, String title,
			String description, String url) {
		this.articlesId = articlesId;
		this.title = title;
		this.description = description;
		this.url = url;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "articles_id")
	public Long getArticlesId() {
		return this.articlesId;
	}

	public void setArticlesId(Long articlesId) {
		this.articlesId = articlesId;
	}

	@Column(name = "title", length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "url", length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
	
	@Column(name = "pic_url", length = 200)
	public String getPicUrl() {
		return picUrl;
	}
	
	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl;
	}

}
