package com.weixin.datacore.domain.weixin.model;
// default package
// Generated 2014-2-10 14:50:02 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WeixinArticles generated by hbm2java
 */
@Entity
@Table(name = "weixin_articles", catalog = "jforum")
public class WeixinArticles implements java.io.Serializable {

	private Long id;
	private String title;
	private String description;
	private String url;
	private String picUrl;
	private int picType;
	private int status;
	private Date createTime;
	private String extend1;
	private String extend2;
	private String operatorId;
	private String operatorName;
	private String platformTag;
	private Date updateTime;

	public WeixinArticles() {
	}

	public WeixinArticles(int picType, int status) {
		this.picType = picType;
		this.status = status;
	}

	public WeixinArticles(String title, String description, String url,
			int picType, int status, Date createTime, String extend1,
			String extend2, String operatorId, String operatorName,
			String platformTag, Date updateTime) {
		this.title = title;
		this.description = description;
		this.url = url;
		this.picType = picType;
		this.status = status;
		this.createTime = createTime;
		this.extend1 = extend1;
		this.extend2 = extend2;
		this.operatorId = operatorId;
		this.operatorName = operatorName;
		this.platformTag = platformTag;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "title", length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "url", length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "pic_type", nullable = false)
	public int getPicType() {
		return this.picType;
	}

	public void setPicType(int picType) {
		this.picType = picType;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "extend1", length = 128)
	public String getExtend1() {
		return this.extend1;
	}

	public void setExtend1(String extend1) {
		this.extend1 = extend1;
	}

	@Column(name = "extend2", length = 128)
	public String getExtend2() {
		return this.extend2;
	}

	public void setExtend2(String extend2) {
		this.extend2 = extend2;
	}

	@Column(name = "operator_id", length = 50)
	public String getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(String operatorId) {
		this.operatorId = operatorId;
	}

	@Column(name = "operator_name", length = 128)
	public String getOperatorName() {
		return this.operatorName;
	}

	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}

	@Column(name = "platform_tag", length = 50)
	public String getPlatformTag() {
		return this.platformTag;
	}

	public void setPlatformTag(String platformTag) {
		this.platformTag = platformTag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	
	@Column(name = "pic_url", length = 200)
	public String getPicUrl() {
		return picUrl;
	}

	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl;
	}
}