package com.weixin.datacore.domain.weixin.model;
// default package
// Generated 2014-1-22 16:24:37 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WeixinMessageLog generated by hbm2java
 */
@Entity
@Table(name = "weixin_message_log")
public class WeixinMessageLog implements java.io.Serializable {

	private long msgId;
	private String toUserName;
	private String fromUserName;
	private Date createTime;
	private Integer msgType;
	private String content;
	private String picUrl;
	private String mediaId;
	private String format;
	private String thumbMediaId;
	private Float locationX;
	private Float locationY;
	private Float scale;
	private String label;
	private String title;
	private String description;
	private String url;
	private String platformTag;

	public WeixinMessageLog() {
	}

	public WeixinMessageLog(long msgId) {
		this.msgId = msgId;
	}

	public WeixinMessageLog(long msgId, String toUserName, String fromUserName,
			Date createTime, Integer msgType, String content, String picUrl,
			String mediaId, String format, String thumbMediaId,
			Float locationX, Float locationY, Float scale, String label,
			String title, String description, String url, String platformTag) {
		this.msgId = msgId;
		this.toUserName = toUserName;
		this.fromUserName = fromUserName;
		this.createTime = createTime;
		this.msgType = msgType;
		this.content = content;
		this.picUrl = picUrl;
		this.mediaId = mediaId;
		this.format = format;
		this.thumbMediaId = thumbMediaId;
		this.locationX = locationX;
		this.locationY = locationY;
		this.scale = scale;
		this.label = label;
		this.title = title;
		this.description = description;
		this.url = url;
		this.platformTag = platformTag;
	}

	@Id
	@Column(name = "msg_id", unique = true, nullable = false)
	public long getMsgId() {
		return this.msgId;
	}

	public void setMsgId(long msgId) {
		this.msgId = msgId;
	}

	@Column(name = "to_user_name", length = 128)
	public String getToUserName() {
		return this.toUserName;
	}

	public void setToUserName(String toUserName) {
		this.toUserName = toUserName;
	}

	@Column(name = "from_user_name", length = 128)
	public String getFromUserName() {
		return this.fromUserName;
	}

	public void setFromUserName(String fromUserName) {
		this.fromUserName = fromUserName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "msg_type")
	public Integer getMsgType() {
		return this.msgType;
	}

	public void setMsgType(Integer msgType) {
		this.msgType = msgType;
	}

	@Column(name = "content", length = 2000)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "pic_url", length = 256)
	public String getPicUrl() {
		return this.picUrl;
	}

	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl;
	}

	@Column(name = "media_id", length = 50)
	public String getMediaId() {
		return this.mediaId;
	}

	public void setMediaId(String mediaId) {
		this.mediaId = mediaId;
	}

	@Column(name = "format", length = 50)
	public String getFormat() {
		return this.format;
	}

	public void setFormat(String format) {
		this.format = format;
	}

	@Column(name = "thumb_media_id", length = 128)
	public String getThumbMediaId() {
		return this.thumbMediaId;
	}

	public void setThumbMediaId(String thumbMediaId) {
		this.thumbMediaId = thumbMediaId;
	}

	@Column(name = "location_x", precision = 12, scale = 0)
	public Float getLocationX() {
		return this.locationX;
	}

	public void setLocationX(Float locationX) {
		this.locationX = locationX;
	}

	@Column(name = "location_y", precision = 12, scale = 0)
	public Float getLocationY() {
		return this.locationY;
	}

	public void setLocationY(Float locationY) {
		this.locationY = locationY;
	}

	@Column(name = "scale", precision = 12, scale = 0)
	public Float getScale() {
		return this.scale;
	}

	public void setScale(Float scale) {
		this.scale = scale;
	}

	@Column(name = "label", length = 128)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "title", length = 256)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "url", length = 256)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "platform_tag", length = 50)
	public String getPlatformTag() {
		return this.platformTag;
	}

	public void setPlatformTag(String platformTag) {
		this.platformTag = platformTag;
	}

}
