package com.weixin.datacore.domain.busi.model;
// default package
// Generated 2014-2-14 14:54:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BusiTagRule generated by hbm2java
 */
@Entity
@Table(name = "busi_tag_rule")
public class BusiTagRule implements java.io.Serializable {

	private String id;
	private String tagName;
	private String tagType;
	private String tagRule;
	private Integer buyTimes;
	private Integer visitTimes;
	private Integer callTimes;
	private String source;
	private Float score;
	private Date updateTime;
	private Date createTime;
	private String extend1;
	private String extend2;
	private String platformTag;

	public BusiTagRule() {
	}

	public BusiTagRule(String id) {
		this.id = id;
	}

	public BusiTagRule(String id, String tagName, String tagType,
			String tagRule, Integer buyTimes, Integer visitTimes,
			Integer callTimes, String source, Float score, Date updateTime,
			Date createTime, String extend1, String extend2, String platformTag) {
		this.id = id;
		this.tagName = tagName;
		this.tagType = tagType;
		this.tagRule = tagRule;
		this.buyTimes = buyTimes;
		this.visitTimes = visitTimes;
		this.callTimes = callTimes;
		this.source = source;
		this.score = score;
		this.updateTime = updateTime;
		this.createTime = createTime;
		this.extend1 = extend1;
		this.extend2 = extend2;
		this.platformTag = platformTag;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "tag_name", length = 50)
	public String getTagName() {
		return this.tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

	@Column(name = "tag_type", length = 20)
	public String getTagType() {
		return this.tagType;
	}

	public void setTagType(String tagType) {
		this.tagType = tagType;
	}

	@Column(name = "tag_rule", length = 50)
	public String getTagRule() {
		return this.tagRule;
	}

	public void setTagRule(String tagRule) {
		this.tagRule = tagRule;
	}

	@Column(name = "buy_times")
	public Integer getBuyTimes() {
		return this.buyTimes;
	}

	public void setBuyTimes(Integer buyTimes) {
		this.buyTimes = buyTimes;
	}

	@Column(name = "visit_times")
	public Integer getVisitTimes() {
		return this.visitTimes;
	}

	public void setVisitTimes(Integer visitTimes) {
		this.visitTimes = visitTimes;
	}

	@Column(name = "call_times")
	public Integer getCallTimes() {
		return this.callTimes;
	}

	public void setCallTimes(Integer callTimes) {
		this.callTimes = callTimes;
	}

	@Column(name = "source", length = 50)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Column(name = "score", precision = 12, scale = 0)
	public Float getScore() {
		return this.score;
	}

	public void setScore(Float score) {
		this.score = score;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "extend1", length = 50)
	public String getExtend1() {
		return this.extend1;
	}

	public void setExtend1(String extend1) {
		this.extend1 = extend1;
	}

	@Column(name = "extend2", length = 50)
	public String getExtend2() {
		return this.extend2;
	}

	public void setExtend2(String extend2) {
		this.extend2 = extend2;
	}

	@Column(name = "platform_tag", length = 50)
	public String getPlatformTag() {
		return this.platformTag;
	}

	public void setPlatformTag(String platformTag) {
		this.platformTag = platformTag;
	}

}
