package com.weixin.datacore.domain.busi.model;
// default package
// Generated 2014-2-14 14:54:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BusiViewHouse generated by hbm2java
 */
@Entity
@Table(name = "busi_view_house")
public class BusiViewHouse implements java.io.Serializable {

	private String id;
	private String name;
	private String mobile;
	private String meetTime;
	private Integer isAsk;
	private Integer isStar;
	private String remark;
	private Date updateTime;
	private Date createTime;
	private String extend1;
	private String extend2;
	private String platformTag;

	public BusiViewHouse() {
	}

	public BusiViewHouse(String id) {
		this.id = id;
	}

	public BusiViewHouse(String id, String name, String mobile,
			String meetTime, Integer isAsk, Integer isStar, String remark,
			Date updateTime, Date createTime, String extend1, String extend2,
			String platformTag) {
		this.id = id;
		this.name = name;
		this.mobile = mobile;
		this.meetTime = meetTime;
		this.isAsk = isAsk;
		this.isStar = isStar;
		this.remark = remark;
		this.updateTime = updateTime;
		this.createTime = createTime;
		this.extend1 = extend1;
		this.extend2 = extend2;
		this.platformTag = platformTag;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "mobile", length = 20)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "meet_time", length = 50)
	public String getMeetTime() {
		return this.meetTime;
	}

	public void setMeetTime(String meetTime) {
		this.meetTime = meetTime;
	}

	@Column(name = "is_ask")
	public Integer getIsAsk() {
		return this.isAsk;
	}

	public void setIsAsk(Integer isAsk) {
		this.isAsk = isAsk;
	}

	@Column(name = "is_star")
	public Integer getIsStar() {
		return this.isStar;
	}

	public void setIsStar(Integer isStar) {
		this.isStar = isStar;
	}

	@Column(name = "remark", length = 500)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "extend1", length = 50)
	public String getExtend1() {
		return this.extend1;
	}

	public void setExtend1(String extend1) {
		this.extend1 = extend1;
	}

	@Column(name = "extend2", length = 50)
	public String getExtend2() {
		return this.extend2;
	}

	public void setExtend2(String extend2) {
		this.extend2 = extend2;
	}

	@Column(name = "platform_tag", length = 50)
	public String getPlatformTag() {
		return this.platformTag;
	}

	public void setPlatformTag(String platformTag) {
		this.platformTag = platformTag;
	}

}
