package com.weixin.datacore.domain.busi.model;
// default package
// Generated 2014-2-14 14:54:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BusiCouponInfo generated by hbm2java
 */
@Entity
@Table(name = "busi_coupon_info")
public class BusiCouponInfo implements java.io.Serializable {

	private String id;
	private String couponName;
	private String couponLimit;
	private Integer couponTotal;
	private String couponShowUrl;
	private Date couponBegin;
	private Date couponEnd;
	private String couponValue;
	private String couponUseRule;
	private Date upateTime;
	private Date createTime;
	private String extend1;
	private String extend2;
	private String platformTag;

	public BusiCouponInfo() {
	}

	public BusiCouponInfo(String id) {
		this.id = id;
	}

	public BusiCouponInfo(String id, String couponName, String couponLimit,
			Integer couponTotal, String couponShowUrl, Date couponBegin,
			Date couponEnd, String couponValue, String couponUseRule,
			Date upateTime, Date createTime, String extend1, String extend2,
			String platformTag) {
		this.id = id;
		this.couponName = couponName;
		this.couponLimit = couponLimit;
		this.couponTotal = couponTotal;
		this.couponShowUrl = couponShowUrl;
		this.couponBegin = couponBegin;
		this.couponEnd = couponEnd;
		this.couponValue = couponValue;
		this.couponUseRule = couponUseRule;
		this.upateTime = upateTime;
		this.createTime = createTime;
		this.extend1 = extend1;
		this.extend2 = extend2;
		this.platformTag = platformTag;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "coupon_name", length = 50)
	public String getCouponName() {
		return this.couponName;
	}

	public void setCouponName(String couponName) {
		this.couponName = couponName;
	}

	@Column(name = "coupon_limit", length = 20)
	public String getCouponLimit() {
		return this.couponLimit;
	}

	public void setCouponLimit(String couponLimit) {
		this.couponLimit = couponLimit;
	}

	@Column(name = "coupon_total")
	public Integer getCouponTotal() {
		return this.couponTotal;
	}

	public void setCouponTotal(Integer couponTotal) {
		this.couponTotal = couponTotal;
	}

	@Column(name = "coupon_show_url", length = 128)
	public String getCouponShowUrl() {
		return this.couponShowUrl;
	}

	public void setCouponShowUrl(String couponShowUrl) {
		this.couponShowUrl = couponShowUrl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "coupon_begin", length = 19)
	public Date getCouponBegin() {
		return this.couponBegin;
	}

	public void setCouponBegin(Date couponBegin) {
		this.couponBegin = couponBegin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "coupon_end", length = 19)
	public Date getCouponEnd() {
		return this.couponEnd;
	}

	public void setCouponEnd(Date couponEnd) {
		this.couponEnd = couponEnd;
	}

	@Column(name = "coupon_value", length = 50)
	public String getCouponValue() {
		return this.couponValue;
	}

	public void setCouponValue(String couponValue) {
		this.couponValue = couponValue;
	}

	@Column(name = "coupon_use_rule", length = 50)
	public String getCouponUseRule() {
		return this.couponUseRule;
	}

	public void setCouponUseRule(String couponUseRule) {
		this.couponUseRule = couponUseRule;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upate_time", length = 19)
	public Date getUpateTime() {
		return this.upateTime;
	}

	public void setUpateTime(Date upateTime) {
		this.upateTime = upateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "extend1", length = 50)
	public String getExtend1() {
		return this.extend1;
	}

	public void setExtend1(String extend1) {
		this.extend1 = extend1;
	}

	@Column(name = "extend2", length = 50)
	public String getExtend2() {
		return this.extend2;
	}

	public void setExtend2(String extend2) {
		this.extend2 = extend2;
	}

	@Column(name = "platform_tag", length = 50)
	public String getPlatformTag() {
		return this.platformTag;
	}

	public void setPlatformTag(String platformTag) {
		this.platformTag = platformTag;
	}

}
